# STATISTICAL TEST RESULTS ATTRIBUTES
LOG_SIZE_ATTR_NAME = 'log_size'
MODEL_ATTR_NAME = 'model'
K_ATTR_NAME = 'k'
MIN_DIFF_ATTR_NAME = 'min_diff'
ALPHA_ATTR_NAME = 'alpha'
DELTA_ATTR_NAME = 'delta'
NUM_LOGS_ATTR_NAME = 'num_of_logs'
TP_ATTR_NAME = 'tp'
FP_ATTR_NAME = 'fp'
TN_ATT_NAME = 'tn'
FN_ATTR_NAME = 'fn'
PRECISION_ATTR_NAME = 'precision'
RECALL_ATTR_NAME = 'recall'
ACCURACY__ATTR_NAME = 'acc'
EST_ALPHA_ATTR_NAME = 'true_error (tp/tn+fp)'
EST_BETA_ATTR_NAME = 'power (tp/tp+fn)'
TOTAL_TRANSITION_ATTR_NAME = 'total_transition'
PVALUE_ATTR_NAME = 'pvalue'
TRIAL_ATTR_NAME = 'trial'
MODEL_ATTR_NAME = 'model'
STATISTICS_ATTR_NAME = 'statistics'
M1_ATTR_NAME = 'm1'
M2_ATTR_NAME = 'm2'
N1_ATTR_NAME = 'n1'
N2_ATTR_NAME = 'n2'
P1_ATTR_NAME = 'p1'
P2_ATTR_NAME = 'p2'
DIFF_ATTR_NAME = 'diff'
DEG_FR_ATTR_NAME = 'deg_fr'
P_HAT_ATTR_NAME = 'p_hat'
SE_ATTR_NAME = 'se'
T_HAT_ATTR_NAME ='t_hat'



# EXPERIMENTS_RESULTS CONSTANTS
PAIRWISE_COMPARISON_ATTR_NAME = 'pairwise_comparisons'
SIGNIFICANT_DIFF_ATTR_NAME ='significant_diff'
DIFFERENT_IDS_ATTR_NAME = 'different_ids'
EXPERIMENTS_PER_LOG_ATTR_NAME = 'experiments_per_log'
COUNT_SIGNIFICANT_DIFFS_ATTR_NAME = 'count_significant_diffs'
MUTIPLE_PROPORTION_TEST_SIGNIFICANT_ATTR_NAME = 'mutiple_proportion_test_significant'
LABEL_ATTR_NAME = 'label'
TRACES_ATTR_NAME = 'traces'
SOURCE_ATTR_NAME = 'source'
TARGET_ATTR_NAME = 'target'

# TIMING EXPERIMENTS_RESULTS CONSTANTS
READ_TIME_ATTRIBUTE = "read_time"
FIND_DIFF_ALG_TIME_ATTRIBUTE = "find_diff_time"
KTAILS_TIME_ATTRIBUTE = "ktails_time"
GRAPH_OVERLAY_TIME_ATTRIBUTE = "overlay_time"

# GRAPHS ATTRIBUTE CONSTANTS
TRANSITION_PROBABILITY_ATTRIBUTE = 'transition_probability'
TRANSITION_LABEL_ATTRIBUTE = 'label'
TOTAL_TRANSITIONS_ATTRIBUTE = 'total_transitions'